[package]
authors = ["Corentin Henry <corentinhenry@gmail.com>"]
name = "netlink-packet-route"
version = "0.24.0"
edition = "2021"

homepage = "https://github.com/rust-netlink/netlink-packet-route"
keywords = ["netlink", "linux"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/rust-netlink/netlink-packet-route"
description = "netlink packet types"

[features]
rich_nlas = []

[dependencies]
anyhow = "1.0.102"
bitflags = "2"
byteorder = "1.5.0"
libc = "0.2.186"
log = { version = "0.4.30", features = ["std"] }
netlink-packet-core = { version = "0.8.1" }
netlink-packet-utils = { version = "0.5.2" }

[[example]]
name = "dump_packet_links"

[dev-dependencies]
netlink-sys = { version = "0.8.8" }
pretty_assertions = "1.4.1"
